// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {services} from '../models';
import {models} from '../models';

export function AddSingleAccount(arg1:string,arg2:string,arg3:string):Promise<main.ImportResult>;

export function ApplySeamlessPatch(arg1:string):Promise<services.PatchResult>;

export function ApplyToolbarLayout(arg1:boolean):Promise<void>;

export function AutoSwitchToNext(arg1:string,arg2:string):Promise<string>;

export function CheckPatchStatus(arg1:string):Promise<boolean>;

export function ControlBackgroundService(arg1:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteExpiredAccounts():Promise<number>;

export function DeleteFreePlanAccounts():Promise<number>;

export function FindWindsurfPath():Promise<string>;

export function GetAllAccounts():Promise<Array<models.Account>>;

export function GetAppStoragePath():Promise<string>;

export function GetBackgroundServiceStatus():Promise<main.BackgroundServiceStatus>;

export function GetCurrentWindsurfAuth():Promise<services.WindsurfAuthJSON>;

export function GetDesktopRuntimeStatus():Promise<main.DesktopRuntimeStatus>;

export function GetMitmCAPath():Promise<string>;

export function GetMitmDebugDumpEnabled():Promise<boolean>;

export function GetMitmProxyStatus():Promise<services.MitmProxyStatus>;

export function GetOpenAIRelayStatus():Promise<services.OpenAIRelayStatus>;

export function GetProtoDumpDir():Promise<string>;

export function GetSettings():Promise<models.Settings>;

export function GetWindsurfAuthPath():Promise<string>;

export function ImportByAPIKey(arg1:Array<main.APIKeyItem>):Promise<Array<main.ImportResult>>;

export function ImportByEmailPassword(arg1:Array<main.EmailPasswordItem>):Promise<Array<main.ImportResult>>;

export function ImportByJWT(arg1:Array<main.JWTItem>):Promise<Array<main.ImportResult>>;

export function ImportByRefreshToken(arg1:Array<main.TokenItem>):Promise<Array<main.ImportResult>>;

export function OpenAccountInIsolatedWindow(arg1:string):Promise<string>;

export function RefreshAccountQuota(arg1:string):Promise<void>;

export function RefreshAllQuotas():Promise<Record<string, string>>;

export function RefreshAllTokens():Promise<Record<string, string>>;

export function RestoreMainWindowLayout():Promise<void>;

export function RestoreSeamlessPatch(arg1:string):Promise<void>;

export function SetSilentFromFlag(arg1:boolean):Promise<void>;

export function SetupMitmCA():Promise<void>;

export function SetupMitmHosts():Promise<void>;

export function StartMitmProxy():Promise<void>;

export function StartOpenAIRelay(arg1:number,arg2:string):Promise<void>;

export function StopMitmProxy():Promise<void>;

export function StopOpenAIRelay():Promise<void>;

export function SwitchAccount(arg1:string):Promise<void>;

export function TeardownMitm():Promise<void>;

export function ToggleMitmDebugDump(arg1:boolean):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
