// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSingleAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSingleAccount'](arg1, arg2, arg3);
}

export function ApplyAllPerformanceFixes() {
  return window['go']['main']['App']['ApplyAllPerformanceFixes']();
}

export function ApplyPerformanceFix(arg1) {
  return window['go']['main']['App']['ApplyPerformanceFix'](arg1);
}

export function CleanupAllSafe() {
  return window['go']['main']['App']['CleanupAllSafe']();
}

export function CleanupStartupCache() {
  return window['go']['main']['App']['CleanupStartupCache']();
}

export function CleanupWindsurf(arg1) {
  return window['go']['main']['App']['CleanupWindsurf'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteAccountsByGroup(arg1) {
  return window['go']['main']['App']['DeleteAccountsByGroup'](arg1);
}

export function DeleteAllUsage() {
  return window['go']['main']['App']['DeleteAllUsage']();
}

export function DeleteExpiredAccounts() {
  return window['go']['main']['App']['DeleteExpiredAccounts']();
}

export function DeleteFreePlanAccounts() {
  return window['go']['main']['App']['DeleteFreePlanAccounts']();
}

export function ExportAccountsByGroup(arg1) {
  return window['go']['main']['App']['ExportAccountsByGroup'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function GetCaptureDir() {
  return window['go']['main']['App']['GetCaptureDir']();
}

export function GetMitmCAPath() {
  return window['go']['main']['App']['GetMitmCAPath']();
}

export function GetMitmDebugDumpEnabled() {
  return window['go']['main']['App']['GetMitmDebugDumpEnabled']();
}

export function GetMitmFullCaptureEnabled() {
  return window['go']['main']['App']['GetMitmFullCaptureEnabled']();
}

export function GetMitmProxyStatus() {
  return window['go']['main']['App']['GetMitmProxyStatus']();
}

export function GetMitmSessionBindings() {
  return window['go']['main']['App']['GetMitmSessionBindings']();
}

export function GetOpenAIRelayStatus() {
  return window['go']['main']['App']['GetOpenAIRelayStatus']();
}

export function GetPerformanceTips() {
  return window['go']['main']['App']['GetPerformanceTips']();
}

export function GetProtoDumpDir() {
  return window['go']['main']['App']['GetProtoDumpDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStaticCacheDir() {
  return window['go']['main']['App']['GetStaticCacheDir']();
}

export function GetUsageRecords(arg1) {
  return window['go']['main']['App']['GetUsageRecords'](arg1);
}

export function GetUsageSummary() {
  return window['go']['main']['App']['GetUsageSummary']();
}

export function GetWindsurfDiskUsage() {
  return window['go']['main']['App']['GetWindsurfDiskUsage']();
}

export function GetWindsurfProcessInfo() {
  return window['go']['main']['App']['GetWindsurfProcessInfo']();
}

export function ImportByAPIKey(arg1) {
  return window['go']['main']['App']['ImportByAPIKey'](arg1);
}

export function ImportByEmailPassword(arg1) {
  return window['go']['main']['App']['ImportByEmailPassword'](arg1);
}

export function ImportByJWT(arg1) {
  return window['go']['main']['App']['ImportByJWT'](arg1);
}

export function ImportByRefreshToken(arg1) {
  return window['go']['main']['App']['ImportByRefreshToken'](arg1);
}

export function RefreshAccountQuota(arg1) {
  return window['go']['main']['App']['RefreshAccountQuota'](arg1);
}

export function RefreshAllQuotas() {
  return window['go']['main']['App']['RefreshAllQuotas']();
}

export function RefreshAllTokens() {
  return window['go']['main']['App']['RefreshAllTokens']();
}

export function SetSilentFromFlag(arg1) {
  return window['go']['main']['App']['SetSilentFromFlag'](arg1);
}

export function SetupMitmCA() {
  return window['go']['main']['App']['SetupMitmCA']();
}

export function SetupMitmHosts() {
  return window['go']['main']['App']['SetupMitmHosts']();
}

export function StartMitmProxy() {
  return window['go']['main']['App']['StartMitmProxy']();
}

export function StartOpenAIRelay(arg1, arg2) {
  return window['go']['main']['App']['StartOpenAIRelay'](arg1, arg2);
}

export function StopMitmProxy() {
  return window['go']['main']['App']['StopMitmProxy']();
}

export function StopOpenAIRelay() {
  return window['go']['main']['App']['StopOpenAIRelay']();
}

export function SwitchMitmToAccount(arg1) {
  return window['go']['main']['App']['SwitchMitmToAccount'](arg1);
}

export function SwitchMitmToNext() {
  return window['go']['main']['App']['SwitchMitmToNext']();
}

export function TeardownMitm() {
  return window['go']['main']['App']['TeardownMitm']();
}

export function ToggleMitmDebugDump(arg1) {
  return window['go']['main']['App']['ToggleMitmDebugDump'](arg1);
}

export function ToggleMitmFullCapture(arg1) {
  return window['go']['main']['App']['ToggleMitmFullCapture'](arg1);
}

export function UnbindMitmSession(arg1) {
  return window['go']['main']['App']['UnbindMitmSession'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
