// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSingleAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSingleAccount'](arg1, arg2, arg3);
}

export function ApplyToolbarLayout(arg1) {
  return window['go']['main']['App']['ApplyToolbarLayout'](arg1);
}

export function ControlBackgroundService(arg1) {
  return window['go']['main']['App']['ControlBackgroundService'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteAccountsByGroup(arg1) {
  return window['go']['main']['App']['DeleteAccountsByGroup'](arg1);
}

export function DeleteExpiredAccounts() {
  return window['go']['main']['App']['DeleteExpiredAccounts']();
}

export function DeleteFreePlanAccounts() {
  return window['go']['main']['App']['DeleteFreePlanAccounts']();
}

export function ExportAccountsByGroup(arg1) {
  return window['go']['main']['App']['ExportAccountsByGroup'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function GetBackgroundServiceStatus() {
  return window['go']['main']['App']['GetBackgroundServiceStatus']();
}

export function GetDesktopRuntimeStatus() {
  return window['go']['main']['App']['GetDesktopRuntimeStatus']();
}

export function GetMitmCAPath() {
  return window['go']['main']['App']['GetMitmCAPath']();
}

export function GetMitmDebugDumpEnabled() {
  return window['go']['main']['App']['GetMitmDebugDumpEnabled']();
}

export function GetMitmProxyStatus() {
  return window['go']['main']['App']['GetMitmProxyStatus']();
}

export function GetOpenAIRelayStatus() {
  return window['go']['main']['App']['GetOpenAIRelayStatus']();
}

export function GetProtoDumpDir() {
  return window['go']['main']['App']['GetProtoDumpDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportByAPIKey(arg1) {
  return window['go']['main']['App']['ImportByAPIKey'](arg1);
}

export function ImportByEmailPassword(arg1) {
  return window['go']['main']['App']['ImportByEmailPassword'](arg1);
}

export function ImportByJWT(arg1) {
  return window['go']['main']['App']['ImportByJWT'](arg1);
}

export function ImportByRefreshToken(arg1) {
  return window['go']['main']['App']['ImportByRefreshToken'](arg1);
}

export function RefreshAccountQuota(arg1) {
  return window['go']['main']['App']['RefreshAccountQuota'](arg1);
}

export function RefreshAllQuotas() {
  return window['go']['main']['App']['RefreshAllQuotas']();
}

export function RefreshAllTokens() {
  return window['go']['main']['App']['RefreshAllTokens']();
}

export function RestoreMainWindowLayout() {
  return window['go']['main']['App']['RestoreMainWindowLayout']();
}

export function SetSilentFromFlag(arg1) {
  return window['go']['main']['App']['SetSilentFromFlag'](arg1);
}

export function SetupMitmCA() {
  return window['go']['main']['App']['SetupMitmCA']();
}

export function SetupMitmHosts() {
  return window['go']['main']['App']['SetupMitmHosts']();
}

export function StartMitmProxy() {
  return window['go']['main']['App']['StartMitmProxy']();
}

export function StartOpenAIRelay(arg1, arg2) {
  return window['go']['main']['App']['StartOpenAIRelay'](arg1, arg2);
}

export function StopMitmProxy() {
  return window['go']['main']['App']['StopMitmProxy']();
}

export function StopOpenAIRelay() {
  return window['go']['main']['App']['StopOpenAIRelay']();
}

export function SwitchMitmToAccount(arg1) {
  return window['go']['main']['App']['SwitchMitmToAccount'](arg1);
}

export function SwitchMitmToNext() {
  return window['go']['main']['App']['SwitchMitmToNext']();
}

export function TeardownMitm() {
  return window['go']['main']['App']['TeardownMitm']();
}

export function ToggleMitmDebugDump(arg1) {
  return window['go']['main']['App']['ToggleMitmDebugDump'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
